#define DISPLAY_ROW_SIZE	16

#define MENU_BUTTONS_PORT	PORTD
#define MENU_BUTTONS_DDR	DDRD
#define MENU_BUTTONS_PIN	PIND
#define MENU_ENTER_BUTTON	PD0
#define MENU_NEXT_BUTTON	PD1
#define MENU_PREV_BUTTON	PD2
#define MENU_ESC_BUTTON		PD3